only:
  triggerType:
    - pullRequest
    - push
  triggerBranch:
    prTargetBranch:
      - ^master$
    pushOriginalBranch:
      - ^master$

onlyExecuteLastPipeline: true

stages:
  - Check
  - Release

STC:
  stage: Check
  plugin: STC
  pluginConfig:
    checkPoints: alipay
  checkRule:
    - stc = 0
  allowFailure: true

PMD:
  stage: Check
  plugin: PMD
  pluginConfig:
    encoding: UTF-8
    excludes:
      - "**/test/**"
    enableAdditional: true
  checkRule:
    - pmd1 = 0 && pmd2 = 0
  allowFailure: true

Build:
  stage: Check
  steps:
    - plugin: clone
    - plugin: cache
      inputs:
        type: restore
        key: maven-repo-{{ checksum 'pom.xml' }}
    - plugin: shell
      inputs:
        image: reg.docker.alibaba-inc.com/antb/sofaboot-build:1.0.0
        command: |
          export PATH=$PATH:/opt/taobao/java/bin:/opt/taobao/maven/bin
          java -version
          mvn -version
          cd $WORKSPACE
          mvn -U -Dmaven.test.skip=true -Dmaven.repo.local=.mvn_repo package
    - plugin: cache
      inputs:
        type: upload
        key: maven-repo-{{ checksum 'pom.xml' }}
        paths: .mvn_repo
